name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["2.2.X"]
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: install deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.version }}

      - name: disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: run checks
        run: deno task check

      - name: run tests
        run: deno task test:ci
